/*
 * Phenom_IO.h
 *
 * Created: 6/22/2013 10:33:50 AM
 *  Author: Chris
 */ 


#ifndef PHENOM_IO_H_
#define PHENOM_IO_H_

#include <avr/io.h>

#define MARKER_TRIGGER_DD_REG       DDRA
#define MARKER_TRIGGER_DD_BIT       DDA6
#define MARKER_TRIGGER_PORT_REG     PORTA
#define MARKER_TRIGGER_PORT_BIT     PORTA6
#define MARKER_TRIGGER_PIN_REG      PINA
#define MARKER_TRIGGER_PIN_BIT      PINA6
#define MARKER_TRIGGER_PULLED_VAL   0
#define MARKER_TRIGGER_RELEASED_VAL 1

#define PHENOM_TRIGGER_DDR   DDRA
#define PHENOM_TRIGGER_PORT  PORTA
#define PHENOM_TRIGGER_PIN   PINA
#define PHENOM_TRIGGER_BIT   PINA6
#define PHENOM_TRIGGER_PRESSED 0
#define PHENOM_TRIGGER_RELEASED 1

#define PHENOM_PUSHBUTTON_DDR   DDRB
#define PHENOM_PUSHBUTTON_PORT  PORTB
#define PHENOM_PUSHBUTTON_PIN   PINB
#define PHENOM_PUSHBUTTON_BIT   1
#define PHENOM_PUSHBUTTON_PRESSED 0
#define PHENOM_PUSHBUTTON_RELEASED 1

#define MARKER_PUSHBUTTON_DD_REG       DDRB
#define MARKER_PUSHBUTTON_DD_BIT       DDB1
#define MARKER_PUSHBUTTON_PORT_REG     PORTB
#define MARKER_PUSHBUTTON_PORT_BIT     PORTB1
#define MARKER_PUSHBUTTON_PIN_REG      PINB
#define MARKER_PUSHBUTTON_PIN_BIT      PINB1
#define MARKER_PUSHBUTTON_PRESSED_VAL       0
#define MARKER_PUSHBUTTON_RELEASED_VAL      1


#define MARKER_RED_LED_DD_REG       DDRA
#define MARKER_RED_LED_DD_BIT       DDA1
#define MARKER_RED_LED_PORT_REG     PORTA
#define MARKER_RED_LED_PORT_BIT     PORTA1
#define MARKER_RED_LED_PIN_REG      PINA
#define MARKER_RED_LED_PIN_BIT      PINA1
#define MARKER_RED_LED_ON_VAL       1
#define MARKER_RED_LED_OFF_VAL      0

#define MARKER_GREEN_LED_DD_REG       DDRA
#define MARKER_GREEN_LED_DD_BIT       DDA2
#define MARKER_GREEN_LED_PORT_REG     PORTA
#define MARKER_GREEN_LED_PORT_BIT     PORTA2
#define MARKER_GREEN_LED_PIN_REG      PINA
#define MARKER_GREEN_LED_PIN_BIT      PINA2
#define MARKER_GREEN_LED_ON_VAL       1
#define MARKER_GREEN_LED_OFF_VAL      0

#define PHENOM_SOLENOID_DDR   DDRA
#define PHENOM_SOLENOID_PORT  PORTA
#define PHENOM_SOLENOID_PIN   PINA
#define PHENOM_SOLENOID_BIT   7
#define PHENOM_SOLENOID_VALUE_ENERGIZED 1
#define PHENOM_SOLENOID_VALUD_DEENGERGIZED 0

//#define PHENOM_SOLENOID_ARM_DDR_REG     DDRB
//#define PHENOM_SOLENOID_ARM_PORT_REG    PORTB
//#define PHENOM_SOLENOID_ARM_PIN_REG     PINB
//#define PHENOM_SOLENOID_ARM_BIT         0
//#define PHENOM_SOLENOID_ARM_VALUE_ARMED 1
//#define PHENOM_SOLENOID_ARM_VALUE_SAFE  0


#endif /* PHENOM_IO_H_ */